version: '3.9'

services:
  doc-tools:
    image: rakovets/doc-tools:latest
    container_name: doc-tools
    volumes:
      - ./config.yaml:/app/configs/config.yaml
      - ./input:/app/input
      - ./output:/app/output
